dataset:
  path: ${hydra:runtime.cwd}/data
  train: train.csv
  val: val.csv
  test: test.csv

dataloader:
  _target_: dataloaders.chordmixer.ChordMixerDataLoader
  data_path: ${dataset.path}
  batch_size: ${general.batch_size}
  clean_text: true

model:
  _target_: models.chordmixer.ChordMixer
  vocab_size: 160_000
  max_seq_len: 10_000
  track_size: 16
  hidden_size: 196
  mlp_dropout: 0
  layer_dropout: 0
  n_class: 2

trainer:
  _target_: trainers.trainer.Trainer

optimizer:
  learning_rate: 0.0005

wandb:
  project: FNDER
  entity: ravaghi
  name: chordmixer

general:
  seed: 42
  device_id: 0
  compute_class_weights: true
  max_epochs: 10
  batch_size: 50

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs