dataset:
  path: ${hydra:runtime.cwd}/data
  train: train.csv
  val: val.csv
  test: test.csv

dataloader:
  _target_: dataloaders.lstm.LSTMDataLoader
  data_path: ${dataset.path}
  batch_size: ${general.batch_size}
  clean_text: true

model:
  _target_: models.lstm.LSTM
  vocab_size: 160_000
  embedding_dim: 300
  hidden_dim: 128
  n_layers: 2

trainer:
  _target_: trainers.lstm.LSTMTrainer

optimizer:
  learning_rate: 0.0001

wandb:
  project: FNDER
  entity: ravaghi
  name: lstm

general:
  seed: 42
  device_id: 0
  compute_class_weights: true
  max_epochs: 10
  batch_size: 50

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs